### ISSUE TITLE
Is there a way to preload filestack?

### ISSUE THREAD

**Issue by andreyvital** [filestack/filestack-react#42]
Hey guys, I'd like to preload filestack client before the user hits the button for picking a file. This improves our UX since there's a tiny delay between the client load and the actual picker UI render

**Comment by velveteer** [comment]
This would have to be an enhancement to the SDK (filestack-js), since the picker code is loaded at runtime over the network. We have had a similar request to provide the picker assets within the SDK for manual bundling, or to at least offer a separate SDK bundle with the picker code already included. We will be tracking this as an enhancement to filestack-js, and hopefully we can offer it as a fast-follow to the 1.0 release.

**Comment by andreyvital** [comment]
Thanks, @velveteer. That'd be great!

**Comment by nidhi-ag** [comment]
Is it possible now ?

**Comment by AndrzejSala** [comment]
@CentaurWarchief @nidhi-ag 
Hey guys,
You should check out a new 2.0.2 release with newly added preload option.
Now you can control if assets like scripts or styles should be injected at mount or rather on click event.
